# First steps in Python
   Primeiros passos no Python



# Crie um programa que calcule a nota de um aluno e retorne se ele foi aprovado ou não:

In [1]:
n1 = float(input("Digite a primeira nota : "))
n2 = float(input("Digite a segunda nota: "))
m = (n1+n2)/2
print("Sua Media foi", m) 
if m == 5 :
  print("Parabens você foi aprovado !")
else:
  print("Você não foi aprovado !")   

Digite a primeira nota : 5.5
Digite a segunda nota: 6.5
Sua Media foi 6.0
Você não foi aprovado !


# Tabuada Primeira Versão

In [2]:
n = int(input("Digite o numero para criar sua Tabuada."))
m = (n*1,n*2, n*3, n*4, n*5, n*6, n*7, n*8, n*9, n*10 )
print(m)

Digite o numero para criar sua Tabuada.5
(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)


# Tabuada Segunda Versão

In [12]:
n = int(input("Digite o numero para a tabuada"))
n1 = (n*1)
n2 = (n*2)
n3 = (n*3)
n4 = (n*4)
n5 = (n*5)
n6 = (n*6)
n7 = (n*7)
n8 = (n*8)
n9 = (n*9)
n10 = (n*10)
print("1X",n1,"= {}".format(n1))
print("1X",n2,"= {}".format(n2))
print("1X",n3,"= {}".format(n3))
print("1X",n4,"= {}".format(n4))
print("1X",n5,"= {}".format(n5))
print("1X",n6,"= {}".format(n6))
print("1X",n7,"= {}".format(n7))
print("1X",n8,"= {}".format(n8))
print("1X",n9,"= {}".format(n9))
print("1X",n10,"= {}".format(n10))



Digite o numero para a tabuada5
1X 5 = 5
1X 10 = 10
1X 15 = 15
1X 20 = 20
1X 25 = 25
1X 30 = 30
1X 35 = 35
1X 40 = 40
1X 45 = 45
1X 50 = 50


#  Tabuada Terceira Versão

In [5]:
n = int(input("Digite um numero para ver sua tabuada: "))
print('{} x 1 = {} \n {} x 2 = {} \n {} x 3 = {} \n {} x 4 = {} \n {} x 5 = {} \n {} x 6 = {} \n {} x 7 = {} \n {} x 8 = {} \n {} x 9 = {} \n {} x 10 = {}'
.format(n,(n*1),n,(n*2),n,(n*3),n,(n*4),n,(n*5),n,(n*6),n,(n*7),n,(n*8),n,(n*9),n,(n*10)))

Digite um numero para ver sua tabuada: 5
5 x 1 = 5 
 5 x 2 = 10 
 5 x 3 = 15 
 5 x 4 = 20 
 5 x 5 = 25 
 5 x 6 = 30 
 5 x 7 = 35 
 5 x 8 = 40 
 5 x 9 = 45 
 5 x 10 = 50


# Tabuada Quarta Versão

In [4]:
#Tabuada Volume - 4
numero = int(input("Digite o numero para a tabuada: "))

for i in range (1,11):
  print(numero,'X', i, '=',(numero * i))

Digite o numero para a tabuada: 5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


# Crie um algoritmo que leia quanto dinheiro uma pessoa tem na carteira e quantos dolares ela pode comprar cotação 02/06/22 - 1 USD = 4,78 BRL 

In [102]:
n=(float(input("Quanto dinheiro você tem na carteira? ")))
m = n/4.78
print("Você tem {:.2f} dolares!".format(m))

def dolar(dinheiro):
    dinheiro= dinheiro/4.78
    print(f"Voce tem {dinheiro} dolares!")
    
dolar(5000)

#Resolvi fazer um modo em função para ver se facilitava,mais o resultado saiu com mais de 2 casas.

Quanto dinheiro você tem na carteira? 5000
Você tem 1046.03 dolares!
Voce tem 1046.0251046025105 dolares!


# FAÇA UM POGRAMA QUE CONVERTA METROS PARA CENTIMETROS.

In [158]:
print("\t-----Conversor M para CM-----")
#Estava usando INT antes do INPUT mais achei melhor mudar para FLOAT para melhor desempenho.
m = float(input("Informe o valor em metros: "))
c = m*100
print("O valor em centimetro é {}!".format(c))


	-----Conversor M para CM-----
Informe o valor em metros: 500
O valor em centimetro é 50000.0!


# FAÇA UM PROGRAMA PARA UM REAJUSTE SALARIAL 

In [159]:
'''Tenho que arrumar as casas decimais do resultado.
Mesmo caso do exemplo anterior, quando se trabalha com numeros,para mim a melhor opção é float, 
ainda mais se tratanto de dinheiro.'''

print("----Reajuste Sálarial-----")
n = float(input("Digite seu sálario atual: "))
if n < 500:
  print("Seu salario é menor que R$ 500.00 e será reajustado em 15% ")
  print("Seu salario atual é",n*1.15)
elif (n >= 500)and (n <=1000):
  print("Seu salario é maior que R$ 500.00 e menor que R$1000.00 será reajustado em 10% ")
  print("Seu salario atual é", n*1.10)
elif n > 1000:
  print("Seu salario é maior que R$ 1000.00 e será reajustado em 5% ")
  print("Seu salario atual é",n*1.05)    

----Reajuste Sálarial-----
Digite seu sálario atual: 5008
Seu salario é maior que R$ 1000.00 e será reajustado em 5% 
Seu salario atual é 5258.400000000001


In [160]:
'''Uma versão usando função.'''
def reajuste_salario():
    salario = float(input("Digite o seu sálario atual: "))
    if salario < 500:
        print("Seu salario é menor que R$ 500.00 e será reajustado em 15% ")
        print("Seu salario atual é",salario*1.15)
    elif (n >= 500)and (salario <=1000):
        print("Seu salario é maior que R$ 500.00 e menor que R$1000.00 será reajustado em 10% ")
        print("Seu salario atual é", salario*1.10)
    elif n > 1000:
        print("Seu salario é maior que R$ 1000.00 e será reajustado em 5% ")
        print("Seu salario atual é",salario*1.05)  
        
reajuste_salario()

Digite o seu sálario atual: 5800
Seu salario é maior que R$ 1000.00 e será reajustado em 5% 
Seu salario atual é 6090.0


# Informe se um numero é positivo,negativo ou neutro.

In [35]:

x = int(input("Digite um numero: "))
if x < 0 :
  print("Esse numero é negativo!")
elif x == 0:
  print("Esse numero é neutro!")
elif x > 0:
  print("Esse numero é positivo!")    

Digite um numero: 5
Esse numero é positivo!


# Contador

In [14]:
'''Ele ta meio estranho ainda não está como eu gostaria...'''

x = int(input("Digite um numero: "))
n = 0
while x != 0:
  x //= 10
  n += 1
  print("total de digitos = ", n) 
  


Digite um numero: 4500
total de digitos =  1
total de digitos =  2
total de digitos =  3
total de digitos =  4


# Algumas simulações com a biblioteca random.

In [75]:
import random
city = ["Barretos" ,"Colina" ,"São Joaquim" ,"Miguelopolis","Guaira"]

city2 = ["São Paulo","Rio de Janeiro","Belo Horizonte","Maceió","Tocantins"]

for i in city2:
    city.append(i)

city.append("Ipuã")



sort = random.choice(city)

print("A Cidade Escolhida é : {}".format(sort))     #Exibição com .format
print("A Cidade Escolhida é :",sort)                #Exibição com STR


A Cidade Escolhida é : Belo Horizonte
A Cidade Escolhida é : Belo Horizonte


In [161]:
#Versão com função
'''Aqui foi criado duas listas, onde uma foi integrada na outra, e depois um elemento a mais foi adicionado com o comando 
.append usando o comando random.choice para poder definir a cidade aleatoriamente.'''

import random
def cidades():
    city = ["Barretos" ,"Colina" ,"São Joaquim" ,"Miguelopolis","Guaira"]
    city2 = ["São Paulo","Rio de Janeiro","Belo Horizonte","Maceió","Tocantins"]
    for i in city2:
        city.append(i)
        city.append("Ipuã")
        
aleatorio = random.choice(city)
print(f"A cidade Sorteada foi: {aleatorio}")


    

A cidade Sorteada foi: Belo Horizonte


# Criar uma nova lista com todos os elementos sendo float

In [162]:
x = [2,4,10,6]
y = []
for i in x:
  y.append(float(i))
  print(y)

[2.0]
[2.0, 4.0]
[2.0, 4.0, 10.0]
[2.0, 4.0, 10.0, 6.0]


# Dicionarios
Iniciando os trabalhos com dicionarios.

In [168]:
'''Apesar de serem poucas linhas ajudam a ter uma noção de como funciona um dicionario'''

x = {"Frota":'61069',"Peso":27800,'Tara':11100}
x['Hora']='11:30' #Adição de um novo indice
print(x)

{'Frota': '61069', 'Peso': 27800, 'Tara': 11100, 'Hora': '11:30'}


# DATAFRAME
Inicio a Dataframe com o Pandas

In [2]:
import pandas as pd

data = {'Nome': ['John','Anna','Peter','Linda'],
        'Location':['New York','London','Paris','Berlin'],
        'Age':[25,33,26,29]}
             
x = pd.DataFrame(data)

display(x)        

Nome  Location  Age
0   John  New York   25
1   Anna    London   33
2  Peter     Paris   26
3  Linda    Berlin   29

# Trabalhando com STRING

In [30]:
x= 'Estou gostando muito de Python'
z= len(x) #Retorna a quantidade de caracteres.
c= x.replace('gostando','adorando') #Substituiu "gostando" por "adorando"
v= x.count('o') #Conta a quantidade de letras "o" na string x

print(v)

5


# Funções
Criação de Funções

In [31]:
def somaNum():
  soma=float(input("Digite um numero: "))
  soma1=float(input("Digite outro numero: "))
  soma3 = soma + soma1
  print("O resultado é {}".format(soma3))
  if soma3 > 10:
    print("Então está bão")
  else:
    print("Então não esta bão")  
      

In [50]:
#Versão simplificada.

def soma_numero(x,y):
    conta = x+y 
    if conta > 10:
        print("Então é maior que 10")
    else:
        print("Nossa nunca imaginei que seria menor que 10!")
 
soma_numero(5,3)

Nossa nunca imaginei que seria menor que 10!


# Função Lambda

In [62]:
somaquadrado = lambda a,b: a**2 + b**2
somaquadrado(10,9)

181

# Função MAP()

In [73]:
kmh = [15,20,36,45,58,60,79,90,120]
mph = []
    for i in kmh:
    mph.append(i/1.61)
         print(mph)

mph2 = list(map(lambda x: x/1.61,kmh))
print(mph2)

IndentationError: unexpected indent (Temp/ipykernel_748/3134628609.py, line 3)

In [80]:
#Versão 1
kmh = [15,20,36,45,58,60,79,90,120]
mph = []
for i in kmh:
    mph.append(i/1.61)
    print(mph)
    
#Versão 2 - LAMBDA
mph2 = list(map(lambda x: x/1.61,kmh))
print(mph2)

#Versão 3
mph3 = [x/1.61 for x in kmh]
print(mph3)

[9.316770186335404]
[9.316770186335404, 12.422360248447204]
[9.316770186335404, 12.422360248447204, 22.360248447204967]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621, 36.024844720496894]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621, 36.024844720496894, 37.267080745341616]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621, 36.024844720496894, 37.267080745341616, 49.06832298136646]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621, 36.024844720496894, 37.267080745341616, 49.06832298136646, 55.90062111801242]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621, 36.024844720496894, 37.267080745341616, 49.06832298136646, 55.90062111801242, 74.53416149068323]
[9.316770186335404, 12.422360248447204, 22.360248447204967, 27.95031055900621, 36.024844720496894, 37.2670807453

# Começando com o Numpy


In [102]:
import numpy as np
a = np.array([(1,5,9),(2,5,8),(3,5,7)]) #Forma uma matriz
print(a)

[[1 5 9]
 [2 5 8]
 [3 5 7]]


In [101]:
'''eye cria matriz com 0 e 1 sendo o 1 na diagonal principal , "matriz identidade" ,ones cria arrey e matrizes,
 ###primeiro digito é sempre linha e o segundo coluna### '''
b = np.eye(10)
c = np.ones((10,3))
v = np.ones(5)
print(c)                   

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [107]:
'''Apos definir uma função numpy pode se usar ela para saber a media,max,min.
   nesse caso a foi definido como uma função do numpy e pode ser usado.  '''
a.max() 
a.mean()
a.min()

1